import type { LifeArena } from "@/types/life-arenas"

export const defaultArenas: LifeArena[] = [
  {
    id: "arena-1",
    name: "Physical Health & Fitness",
    description: "Your body is your temple - physical vitality and wellness",
    currentScore: 6,
    targetScore: 9,
    gradient: "from-red-500 to-orange-600",
    visionStatement:
      "I maintain optimal physical health through consistent exercise, proper nutrition, and adequate rest. My body serves as a strong foundation for all other areas of my life.",
    currentActions: [
      "Exercise 5 times per week",
      "Eat 5 servings of vegetables daily",
      "Get 7-8 hours of sleep nightly",
    ],
    milestones: [
      {
        id: "m1",
        title: "Complete first 5K run",
        description: "Build cardiovascular endurance",
        targetDate: "2024-03-15",
        completed: true,
        completedDate: "2024-03-10",
      },
      {
        id: "m2",
        title: "Achieve target weight",
        description: "Reach optimal body composition",
        targetDate: "2024-06-01",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-20",
    salPrinciple: "Physical stewardship enables mental clarity and spiritual strength",
    icon: "💪",
  },
  {
    id: "arena-2",
    name: "Mental & Emotional Wellness",
    description: "Inner peace, emotional intelligence, and mental resilience",
    currentScore: 7,
    targetScore: 9,
    gradient: "from-purple-500 to-pink-600",
    visionStatement:
      "I maintain emotional balance and mental clarity through mindfulness, self-awareness, and continuous learning. I respond rather than react to life's challenges.",
    currentActions: ["Daily meditation practice", "Weekly therapy sessions", "Read personal development books"],
    milestones: [
      {
        id: "m3",
        title: "Complete mindfulness course",
        description: "Develop consistent meditation practice",
        targetDate: "2024-02-28",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-18",
    salPrinciple: "Emotional mastery is the foundation of self-action leadership",
    icon: "🧠",
  },
  {
    id: "arena-3",
    name: "Relationships & Social",
    description: "Meaningful connections and social contribution",
    currentScore: 8,
    targetScore: 9,
    gradient: "from-blue-500 to-cyan-600",
    visionStatement:
      "I cultivate deep, meaningful relationships and contribute positively to my community. I am a source of support and inspiration for others.",
    currentActions: ["Weekly family time", "Monthly friend gatherings", "Volunteer at local charity"],
    milestones: [
      {
        id: "m4",
        title: "Organize family reunion",
        description: "Strengthen family bonds",
        targetDate: "2024-07-04",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-22",
    salPrinciple: "Service to others is the highest form of leadership",
    icon: "👥",
  },
  {
    id: "arena-4",
    name: "Career & Professional",
    description: "Purpose-driven work and professional excellence",
    currentScore: 8,
    targetScore: 10,
    gradient: "from-green-500 to-emerald-600",
    visionStatement:
      "I excel in my career by aligning my work with my values and continuously developing my skills. I make a meaningful impact through my professional contributions.",
    currentActions: ["Complete professional certification", "Mentor junior colleagues", "Lead strategic initiatives"],
    milestones: [
      {
        id: "m5",
        title: "Earn promotion to senior role",
        description: "Advance career trajectory",
        targetDate: "2024-12-31",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-19",
    salPrinciple: "Excellence in work is a form of service and self-expression",
    icon: "💼",
  },
  {
    id: "arena-5",
    name: "Financial Freedom",
    description: "Financial intelligence and abundance mindset",
    currentScore: 5,
    targetScore: 8,
    gradient: "from-yellow-500 to-amber-600",
    visionStatement:
      "I achieve financial independence through wise investments, disciplined spending, and multiple income streams. Money serves my values and goals.",
    currentActions: ["Save 20% of income monthly", "Invest in index funds", "Track expenses weekly"],
    milestones: [
      {
        id: "m6",
        title: "Build 6-month emergency fund",
        description: "Establish financial security",
        targetDate: "2024-08-01",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-21",
    salPrinciple: "Financial stewardship enables freedom and service",
    icon: "💰",
  },
  {
    id: "arena-6",
    name: "Spiritual Development",
    description: "Connection to purpose, meaning, and transcendence",
    currentScore: 7,
    targetScore: 9,
    gradient: "from-indigo-500 to-purple-600",
    visionStatement:
      "I maintain a deep connection to my spiritual beliefs and live according to universal principles. I find meaning and purpose in all aspects of life.",
    currentActions: ["Daily prayer/meditation", "Weekly spiritual study", "Regular service activities"],
    milestones: [
      {
        id: "m7",
        title: "Complete spiritual retreat",
        description: "Deepen spiritual practice",
        targetDate: "2024-05-15",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-17",
    salPrinciple: "Spiritual alignment guides all other life decisions",
    icon: "🙏",
  },
  {
    id: "arena-7",
    name: "Personal Growth & Learning",
    description: "Continuous learning and skill development",
    currentScore: 8,
    targetScore: 9,
    gradient: "from-teal-500 to-green-600",
    visionStatement:
      "I am committed to lifelong learning and personal development. I continuously expand my knowledge, skills, and understanding of the world.",
    currentActions: ["Read 2 books per month", "Take online courses", "Attend workshops and seminars"],
    milestones: [
      {
        id: "m8",
        title: "Complete SAL Master Challenge",
        description: "Finish all 8 books and requirements",
        targetDate: "2024-12-31",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-23",
    salPrinciple: "Growth is the essence of life and leadership",
    icon: "📚",
  },
  {
    id: "arena-8",
    name: "Recreation & Adventure",
    description: "Joy, play, and life experiences",
    currentScore: 6,
    targetScore: 8,
    gradient: "from-pink-500 to-rose-600",
    visionStatement:
      "I maintain balance through regular recreation, adventure, and play. I create joyful memories and experiences that enrich my life.",
    currentActions: ["Plan monthly adventures", "Try new hobbies", "Schedule regular fun activities"],
    milestones: [
      {
        id: "m9",
        title: "Take dream vacation",
        description: "Experience new culture and adventure",
        targetDate: "2024-09-01",
        completed: false,
      },
    ],
    lastUpdated: "2024-01-16",
    salPrinciple: "Joy and recreation restore the soul for greater service",
    icon: "🎯",
  },
] 