import type { SALTask, CategoryConfig } from "@/types/tasks"

export const categoryConfig: Record<string, CategoryConfig> = {
  foundation: { color: "from-slate-500 to-gray-600", icon: "🏗️", label: "Foundation" },
  knowledge: { color: "from-blue-500 to-indigo-600", icon: "📚", label: "Knowledge" },
  action: { color: "from-green-500 to-emerald-600", icon: "⚡", label: "Action" },
  reflection: { color: "from-purple-500 to-pink-600", icon: "🤔", label: "Reflection" },
  service: { color: "from-orange-500 to-red-600", icon: "🤝", label: "Service" },
  creation: { color: "from-yellow-500 to-amber-600", icon: "✨", label: "Creation" },
}

export const defaultTasks: SALTask[] = [
  {
    id: 1,
    title: "Obtain Your SAL Journal",
    description:
      "Get a notebook or create an electronic file for your personal SAL Journal to accompany your journey through the textbook. This will be your primary tool for reflection and growth.",
    bookSection: "Book the First",
    category: "foundation",
    status: "completed",
    timeSpent: 15,
    notes: "Using SAL OS digital journal system",
    relatedJournalIds: [],
    relatedArenaIds: [],
    estimatedMinutes: 30,
    isMultiPart: false,
    completedDate: "2024-01-10",
    startedDate: "2024-01-10",
  },
  {
    id: 2,
    title: "Build Your Vocabulary (100 Words)",
    description:
      "Locate 100 words you don't know by reading challenging books. Record each word's part of speech, definition, etymology, and write practice sentences. This builds cultural literacy essential for leadership.",
    bookSection: "Book the First",
    category: "knowledge",
    status: "in-progress",
    timeSpent: 120,
    notes: "Currently at 8/100 words. Focusing on SAL textbook vocabulary.",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-7"],
    estimatedMinutes: 600,
    isMultiPart: true,
    subTasks: ["Find words", "Define words", "Write sentences", "Review regularly"],
    completedSubTasks: 1,
    startedDate: "2024-01-12",
  },
  {
    id: 3,
    title: "Read National History Book",
    description:
      "Read a 200+ page book on a positive aspect of your country's history and reflect on lessons relating to liberty and freedom. Understanding history informs present leadership.",
    bookSection: "Book the Second",
    category: "knowledge",
    status: "not-started",
    timeSpent: 0,
    notes: "",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-7"],
    estimatedMinutes: 480,
    isMultiPart: false,
  },
  {
    id: 4,
    title: "Find an Accountability Partner",
    description:
      "Locate someone who will hold you accountable to complete the SAL Master Challenge. This person should initial each completed exercise and support your growth journey.",
    bookSection: "Book the First",
    category: "foundation",
    status: "not-started",
    timeSpent: 0,
    notes: "",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-3"],
    estimatedMinutes: 60,
    isMultiPart: false,
  },
  {
    id: 5,
    title: "Complete Physical Fitness Challenge",
    description:
      "Design and complete a 30-day physical fitness challenge that pushes your current limits. Physical discipline builds mental and spiritual strength.",
    bookSection: "Book the Third",
    category: "action",
    status: "not-started",
    timeSpent: 0,
    notes: "",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-1"],
    estimatedMinutes: 900,
    isMultiPart: true,
    subTasks: ["Design challenge", "Complete 30 days", "Document progress", "Reflect on growth"],
    completedSubTasks: 0,
  },
  {
    id: 6,
    title: "Write Personal Mission Statement",
    description:
      "Craft a comprehensive personal mission statement that defines your purpose, values, and vision for your life. This becomes your North Star for decision-making.",
    bookSection: "Book the Fourth",
    category: "creation",
    status: "not-started",
    timeSpent: 0,
    notes: "",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-6", "arena-7"],
    estimatedMinutes: 180,
    isMultiPart: false,
  },
  {
    id: 7,
    title: "Conduct Life Arena Assessment",
    description:
      "Thoroughly assess your current state in all 8 life arenas. Rate yourself honestly and create improvement plans for each area.",
    bookSection: "Book the Second",
    category: "reflection",
    status: "in-progress",
    timeSpent: 45,
    notes: "Completed initial assessment, working on improvement plans",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-1", "arena-2", "arena-3", "arena-4", "arena-5", "arena-6", "arena-7", "arena-8"],
    estimatedMinutes: 240,
    isMultiPart: true,
    subTasks: ["Assess current state", "Set targets", "Create action plans", "Begin implementation"],
    completedSubTasks: 2,
    startedDate: "2024-01-15",
  },
  {
    id: 8,
    title: "Memorize SAL Mantras",
    description:
      "Memorize the key SAL mantras and principles. These become mental tools for daily decision-making and character development.",
    bookSection: "Book the First",
    category: "knowledge",
    status: "in-progress",
    timeSpent: 30,
    notes: "Memorized 2 out of 10 key mantras",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-2", "arena-6"],
    estimatedMinutes: 120,
    isMultiPart: true,
    subTasks: ["Identify key mantras", "Practice daily", "Test recall", "Apply in decisions"],
    completedSubTasks: 1,
    startedDate: "2024-01-18",
  },
  {
    id: 9,
    title: "Perform 40 Hours of Service",
    description:
      "Complete 40 hours of meaningful service to others without expectation of reward. Service develops character and connects us to our higher purpose.",
    bookSection: "Book the Fifth",
    category: "service",
    status: "not-started",
    timeSpent: 0,
    notes: "",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-3", "arena-6"],
    estimatedMinutes: 2400,
    isMultiPart: true,
    subTasks: ["Plan service activities", "Complete 40 hours", "Document impact", "Reflect on growth"],
    completedSubTasks: 0,
  },
  {
    id: 10,
    title: "Create Personal Constitution",
    description:
      "Write your personal constitution outlining your fundamental principles, values, and the laws by which you will govern your life.",
    bookSection: "Book the Sixth",
    category: "creation",
    status: "not-started",
    timeSpent: 0,
    notes: "",
    relatedJournalIds: [],
    relatedArenaIds: ["arena-6", "arena-7"],
    estimatedMinutes: 300,
    isMultiPart: false,
  },
] 