import type { MasteryLevel, SourceOption } from "@/types/vocabulary"

export const partOfSpeechOptions = [
  "noun",
  "verb",
  "adjective",
  "adverb",
  "pronoun",
  "preposition",
  "conjunction",
  "interjection",
]

export const sourceOptions: SourceOption[] = [
  { value: "reading", label: "Reading", icon: "📚" },
  { value: "tasks", label: "SAL Tasks", icon: "✅" },
  { value: "manual", label: "Manual Entry", icon: "✏️" },
  { value: "daily", label: "Word of Day", icon: "📅" },
]

export const masteryLevels: MasteryLevel[] = [
  { value: "new", label: "New", color: "from-blue-400 to-blue-600", days: 1 },
  { value: "learning", label: "Learning", color: "from-purple-400 to-purple-600", days: 3 },
  { value: "familiar", label: "Familiar", color: "from-green-400 to-green-600", days: 14 },
  { value: "mastered", label: "Mastered", color: "from-yellow-400 to-amber-600", days: 90 },
]

export const defaultWords = [
  {
    id: "1",
    word: "Ontological",
    partOfSpeech: "adjective",
    definition: "Related to the metaphysical nature of being and existence",
    etymology: "Greek: ontos (being) + logos (study)",
    pronunciation: "on-tuh-LOJ-i-kuhl",
    exampleSentences: [
      "The ontological question of what it means to exist has puzzled philosophers for centuries.",
      "SAL addresses ontological concerns about human purpose and meaning.",
    ],
    synonyms: ["existential", "metaphysical"],
    antonyms: ["empirical", "physical"],
    source: "reading" as const,
    bookReference: "Book the Third - SAL Philosophy",
    dateAdded: "2024-01-10",
    lastReviewed: "2024-01-20",
    reviewCount: 5,
    masteryLevel: "familiar" as const,
    tags: ["philosophy", "SAL concepts"],
    personalNotes: "Key concept in understanding SAL's philosophical foundation",
    nextReviewDate: "2024-02-03",
    difficultyRating: 3,
  },
  {
    id: "2",
    word: "Serendipity",
    partOfSpeech: "noun",
    definition: "The occurrence of events by chance in a happy or beneficial way",
    etymology: "Coined by Horace Walpole from Persian fairy tale 'The Three Princes of Serendip'",
    pronunciation: "ser-uhn-DIP-i-tee",
    exampleSentences: [
      "The serendipity of meeting my mentor changed my life's direction.",
      "SAL teaches us to recognize and create opportunities for serendipity.",
    ],
    synonyms: ["fortune", "luck", "providence"],
    antonyms: ["misfortune", "bad luck"],
    source: "tasks" as const,
    bookReference: "Book the Second - Change, Growth & Freedom",
    dateAdded: "2024-01-12",
    lastReviewed: "2024-01-22",
    reviewCount: 8,
    masteryLevel: "mastered" as const,
    tags: ["SAL concepts", "personal development"],
    personalNotes: "Central to understanding how SAL creates positive life changes",
    nextReviewDate: "2024-04-22",
    difficultyRating: 2,
  },
  {
    id: "3",
    word: "Pedagogy",
    partOfSpeech: "noun",
    definition: "The method and practice of teaching, especially as an academic subject or theoretical concept",
    etymology: "Greek: paidagogos (child-leader)",
    pronunciation: "PED-uh-goh-jee",
    exampleSentences: [
      "Effective pedagogy adapts to different learning styles.",
      "SAL pedagogy emphasizes self-directed learning and character development.",
    ],
    synonyms: ["teaching", "instruction", "education"],
    antonyms: ["ignorance", "miseducation"],
    source: "reading" as const,
    bookReference: "Book the Seventh - Pedagogy",
    dateAdded: "2024-01-15",
    lastReviewed: "2024-01-18",
    reviewCount: 2,
    masteryLevel: "learning" as const,
    tags: ["education", "SAL concepts"],
    personalNotes: "Important for understanding how to teach SAL to others",
    nextReviewDate: "2024-01-25",
    difficultyRating: 3,
  },
  {
    id: "4",
    word: "Authenticism",
    partOfSpeech: "noun",
    definition: "The practice of being genuine and true to one's own personality, spirit, or character",
    etymology: "Latin: authenticus (original, genuine)",
    pronunciation: "aw-THEN-ti-sizm",
    exampleSentences: [
      "Authenticism requires courage to be yourself despite social pressure.",
      "SAL promotes authenticism as a foundation for personal leadership.",
    ],
    synonyms: ["genuineness", "sincerity", "honesty"],
    antonyms: ["pretense", "artificiality", "deception"],
    source: "manual" as const,
    bookReference: "Book the Fourth - SAL Theory",
    dateAdded: "2024-01-18",
    lastReviewed: "2024-01-20",
    reviewCount: 3,
    masteryLevel: "learning" as const,
    tags: ["character", "SAL concepts"],
    personalNotes: "Core principle for developing authentic leadership",
    nextReviewDate: "2024-01-27",
    difficultyRating: 2,
  },
] 